DROP SCHEMA THINKBRUH;

CREATE SCHEMA THINKBRUH;
USE THINKBRUH;

CREATE TABLE `BRAND` (
	`BRAND_ID` 				CHAR(2)			NOT NULL,
    `BRAND_NAME` 			VARCHAR(50)		NOT NULL,
    `BRAND_SHORT_DESC`		VARCHAR(500)			,
    
    PRIMARY KEY(`BRAND_ID`)
);


CREATE TABLE `PRODUCT` (
	`PRO_ID`				CHAR(5)			NOT NULL,
    `PRO_NAME`				VARCHAR(50)		NOT NULL,
    
    `BRAND_ID`				CHAR(2)				NOT NULL,
    `DESC`					VARCHAR(500),

    `PRICE`					INT 			NOT NULL,
    
    PRIMARY KEY (`PRO_ID`),
    FOREIGN KEY (`BRAND_ID`) REFERENCES `BRAND` (`BRAND_ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `INVENTORY` (
	`PRO_ID`				CHAR(5)			NOT NULL,
    `AVAIL_NUM`				int				NOT NULL,
    
    FOREIGN KEY (`PRO_ID`) REFERENCES `PRODUCT` (`PRO_ID`) ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE (`PRO_ID`)
);

CREATE TABLE `SPECS`(
	
    `PRO_ID`				CHAR(5)				NOT NULL,

	`PROCESSOR`				VARCHAR(50)			,
    `DISPLAY`				VARCHAR(50)			,
    `MEMORY`				VARCHAR(50)			,
    `GRAPHICS`				VARCHAR(50)			,
    `STORAGE`				VARCHAR(50)			,
    `BATTERY`				VARCHAR(50)			,
    `PORTS`					VARCHAR(50)			,
    `WEIGHT`				VARCHAR(10)			,
    `OS`					VARCHAR(20),
    
    FOREIGN KEY (`PRO_ID`) REFERENCES	PRODUCT (`PRO_ID`)	ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE(`PRO_ID`)
    
);

CREATE TABLE `USERS` (
	`USER_ID`		CHAR(10)				NOT NULL,
    
    PRIMARY KEY(`USER_ID`)		    
);

CREATE TABLE `ORDERS` (
	`ORDER_ID`				CHAR(8)		NOT NULL,
    `USER_ID`				CHAR(10)		NOT NULL,

    `TOTAL`					INT			NOT NULL,
    
    PRIMARY KEY (`ORDER_ID`) REFERENCES `USERS` (`USER_ID`)
);

CREATE TABLE `ORDER_ITEM` (
	`ITEM_ID`			CHAR(5),
    `ORDER_ID`			CHAR(8),
    `PRO_ID`			CHAR(5),
    `QUANTITY`			INT,
    
    PRIMARY KEY (`ITEM_ID`),
    FOREIGN KEY (`ORDER_ID`) 	REFERENCES	`ORDERS` (`ORDER_ID`)	ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (`PRO_ID`) 		REFERENCES	`PRODUCT` (`PRO_ID`)	ON DELETE CASCADE ON UPDATE CASCADE
    
);

CREATE TABLE `CART` (
	`CART_ID`		CHAR(12),
    `USER_ID`		CHAR(10),
    `TOTAL`			int,
    
    PRIMARY KEY (`CART_ID`),
    FOREIGN KEY (`USER_ID`)	REFERENCES `USERS` (`USER_ID`)	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE `CART_ITEM`(
	`CITEM_ID`		CHAR(15),
    `PRO_ID`		CHAR(5),
    `CART_ID`		CHAR(12),
    `QUANTITY`		INT,
		
	PRIMARY KEY(`CITEM_ID`),
    FOREIGN KEY(`PRO_ID`)	REFERENCES  `PRODUCT` (`PRO_ID`),
	FOREIGN KEY(`CART_ID`)	REFERENCES	`CART`	(`CART_ID`)
);





CREATE TABLE `MEMBERS`
(
	`USERNAME`		VARCHAR(15)			NOT NULL,
	`USER_ID`		CHAR(10)			NOT NULL,
    
    `NAME`			VARCHAR(30)			NOT NULL,
    `PHONE`			VARCHAR(11)			NOT NULL,
    `PASSWORD`		VARCHAR(30)			NOT NULL,
    
    PRIMARY KEY (`USERNAME`),
    UNIQUE (`PHONE`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE ON UPDATE CASCADE
);



    
    

    
